In [102]:
import pandas as pd
link='https://github.com/JohanaCrisos/PC2_Crisostomo/raw/refs/heads/main/HDI.xlsx'
tabla=pd.read_excel(link, header=4)
tabla

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
4,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
tabla.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Human Development Index (HDI) ',
       'Unnamed: 3', 'Life expectancy at birth', 'Unnamed: 5',
       'Expected years of schooling', 'Unnamed: 7', 'Mean years of schooling',
       'Unnamed: 9', 'Gross national income (GNI) per capita', 'Unnamed: 11',
       'GNI per capita rank minus HDI rank', 'Unnamed: 13', 'HDI rank'],
      dtype='object')

In [104]:
#Eliminar filas y columnas innecesarias
toDrop=['Unnamed: 0','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13','GNI per capita rank minus HDI rank', 'HDI rank']
tabla.drop(columns=toDrop, inplace=True)
tabla.drop(index=[0,1], inplace=True)

In [105]:
#quitar los espacios iniciales y finales de las columnas y sustituir
#los espacios entre lineas con _
tabla.columns=tabla.columns.str.strip().str.replace(r'\s+', '_', regex=True)
tabla.columns

Index(['Unnamed:_1', 'Human_Development_Index_(HDI)',
       'Life_expectancy_at_birth', 'Expected_years_of_schooling',
       'Mean_years_of_schooling', 'Gross_national_income_(GNI)_per_capita'],
      dtype='object')

In [106]:
#Renombrar
newname={'Unnamed:_1':'Country','Human_Development_Index_(HDI)':'Human_Development_Index','Gross_national_income_(GNI)_per_capita':'Gross_national_income_per_capita'}
tabla.rename(columns=newname,inplace=True)

In [107]:
tabla

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
2,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
5,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
6,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
...,...,...,...,...,...,...
267,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN
268,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN
269,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN
270,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN
271,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

In [108]:
#Eliminar filas con datos faltantes
tabla=tabla.dropna(axis='rows',how='any', ignore_index=True)
tabla

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...
205,Sub-Saharan Africa,0.547,60.112467,10.267338,6.001639,3698.868914
206,Least developed countries,0.54,64.215856,10.182659,5.21532,2880.652487
207,Small island developing states,0.73,70.325547,12.422289,9.08964,16782.329527
208,Organisation for Economic Co-operation and Dev...,0.899,78.987605,16.459253,12.267755,45086.969067
209,World,0.732,71.365465,12.780907,8.617461,16752.082922

In [109]:
#Eliminar las final que no tengan nada que ver con Country
tabla=tabla.drop(index=range(195,210))
tabla

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...
190,South Sudan,0.385,54.9752,5.54251,5.72614,767.787
191,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
192,Monaco,..,85.9463,..,..,..
193,Nauru,..,63.617,11.69042,..,17729.74084
194,Somalia,..,55.2803,..,..,1017.96785

In [110]:
pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.11/dist-packages (1.3.8)

In [ ]:
#Ahora analizaremos las columnas
#Nos aseguramos que los paises esten correctamente escritos
tabla['Country']=tabla.Country.str.title()

In [111]:
#Columna Human
tabla[tabla.Human_Development_Index.str.contains(r'\D',na=False)] #se identifica los valores que no contienen números

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
191,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
192,Monaco,..,85.9463,..,..,..
193,Nauru,..,63.617,11.69042,..,17729.74084
194,Somalia,..,55.2803,..,..,1017.96785

In [112]:
tabla[tabla.Expected_years_of_schooling.str.contains(r'\D',na=False)]

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
192,Monaco,..,85.9463,..,..,..
194,Somalia,..,55.2803,..,..,1017.96785

In [113]:
tabla[tabla.Gross_national_income_per_capita.str.contains(r'\D',na=False)]

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
191,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
192,Monaco,..,85.9463,..,..,..

In [114]:
tabla[tabla.Mean_years_of_schooling.str.contains(r'\D',na=False)]

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
191,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
192,Monaco,..,85.9463,..,..,..
193,Nauru,..,63.617,11.69042,..,17729.74084
194,Somalia,..,55.2803,..,..,1017.96785

In [115]:
pd.unique(tabla.Life_expectancy_at_birth[~tabla.Life_expectancy_at_birth.astype(str).str.contains(r'\d+\.\d+', regex=True)])

array([], dtype=object)

In [116]:
tabla.Human_Development_Index=pd.to_numeric(tabla.Human_Development_Index, errors='coerce')
tabla.Human_Development_Index

0      0.962
1      0.961
2      0.959
3      0.952
4      0.951
       ...
190    0.385
191      NaN
192      NaN
193      NaN
194      NaN
Name: Human_Development_Index, Length: 195, dtype: float64

In [117]:
tabla.Life_expectancy_at_birth=pd.to_numeric(tabla.Life_expectancy_at_birth, errors='coerce')
tabla.Life_expectancy_at_birth

0      83.9872
1      83.2339
2      82.6782
3      85.4734
4      84.5265
        ...
190    54.9752
191    73.2845
192    85.9463
193    63.6170
194    55.2803
Name: Life_expectancy_at_birth, Length: 195, dtype: float64

In [118]:
tabla.Expected_years_of_schooling=pd.to_numeric(tabla.Expected_years_of_schooling, errors='coerce')
tabla.Expected_years_of_schooling

0      16.500299
1      18.185200
2      19.163059
3      17.278170
4      21.054590
         ...
190     5.542510
191    10.783170
192          NaN
193    11.690420
194          NaN
Name: Expected_years_of_schooling, Length: 195, dtype: float64

In [119]:
tabla.Mean_years_of_schooling=pd.to_numeric(tabla.Mean_years_of_schooling, errors='coerce')
tabla.Mean_years_of_schooling

0      13.85966
1      13.00363
2      13.76717
3      12.22621
4      12.72682
         ...
190     5.72614
191         NaN
192         NaN
193         NaN
194         NaN
Name: Mean_years_of_schooling, Length: 195, dtype: float64

In [120]:
tabla.Gross_national_income_per_capita=pd.to_numeric(tabla.Gross_national_income_per_capita, errors='coerce')
tabla.Gross_national_income_per_capita

0      66933.00454
1      64660.10622
2      55782.04981
3      62606.84540
4      49238.43335
          ...
190      767.78700
191            NaN
192            NaN
193    17729.74084
194     1017.96785
Name: Gross_national_income_per_capita, Length: 195, dtype: float64

In [121]:
tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           195 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expectancy_at_birth          195 non-null    float64
 3   Expected_years_of_schooling       193 non-null    float64
 4   Mean_years_of_schooling           191 non-null    float64
 5   Gross_national_income_per_capita  193 non-null    float64
dtypes: float64(5), object(1)
memory usage: 9.3+ KB

In [122]:
#Categotización
tabla['Category']=pd.cut(tabla.Human_Development_Index,
                         bins=[0,0.549,0.7,0.8,1],
                         labels=['Low Human Development','Medium Human Development','High Human Development','Very High Human Development'],
                         ordered=True)
tabla

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita,Category
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,Very High Human Development
1,Norway,0.961,83.2339,18.185200,13.00363,64660.10622,Very High Human Development
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,Very High Human Development
3,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.22621,62606.84540,Very High Human Development
4,Australia,0.951,84.5265,21.054590,12.72682,49238.43335,Very High Human Development
...,...,...,...,...,...,...,...
190,South Sudan,0.385,54.9752,5.542510,5.72614,767.78700,Low Human Development
191,Korea (Democratic People's Rep. of),NaN,73.2845,10.783170,NaN,NaN,NaN
192,Monaco,NaN,85.9463,NaN,NaN,NaN,NaN
193,Nauru,NaN,63.6170,11.690420,NaN,17729.74084,NaN
194,Somalia,NaN,55.2803,NaN,NaN,1017.96785,NaN

In [123]:
tabla[tabla.isnull().any(axis=1)] #ver los valores nulos

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita,Category
191,Korea (Democratic People's Rep. of),NaN,73.2845,10.78317,NaN,NaN,NaN
192,Monaco,NaN,85.9463,NaN,NaN,NaN,NaN
193,Nauru,NaN,63.6170,11.69042,NaN,17729.74084,NaN
194,Somalia,NaN,55.2803,NaN,NaN,1017.96785,NaN

In [124]:
tabla.dropna(axis='rows',how='any',ignore_index=True) #ignorar los valores nulos

,Country,Human_Development_Index,Life_expectancy_at_birth,Expected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita,Category
0,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,Very High Human Development
1,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,Very High Human Development
2,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,Very High Human Development
3,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,Very High Human Development
4,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,Very High Human Development
...,...,...,...,...,...,...,...
186,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,Low Human Development
187,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,Low Human Development
188,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,Low Human Development
189,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,Low Human Development
190,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,Low Human Development

In [125]:
#lo guardamos usando pickle
tabla.to_pickle("tabla.pkl")
dfPickle=pd.read_pickle("tabla.pkl")
dfPickle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           195 non-null    object
 1   Human_Development_Index           191 non-null    float64
 2   Life_expectancy_at_birth          195 non-null    float64
 3   Expected_years_of_schooling       193 non-null    float64
 4   Mean_years_of_schooling           191 non-null    float64
 5   Gross_national_income_per_capita  193 non-null    float64
 6   Category                          191 non-null    category
dtypes: category(1), float64(5), object(1)
memory usage: 9.5+ KB